[package]
name = "smallpt"
version = "0.1.0"
authors = ["Tim Robinson <tim.g.robinson@gmail.com>"]
build = "build.rs"

[dependencies]
cairo-rs = "0.0.8"
glib = "0.0.8"
rand = "0.3"

[dependencies.gtk]
version = "0.0.7"
features = ["v3_10"]

[build-dependencies]
pkg-config = "0.3"
